### ISSUE TITLE
Installation from repository

### ISSUE THREAD

**Issue by d47081** [SRombauts/SQLiteCpp#490]
I have just found and installed `libsqlitecpp-dev` from Debian 12 repository, suppose it's official even not latest version.

So it's compiling well in VSCode, without errors, by using this header:
``` hpp
#include <SQLiteCpp/SQLiteCpp.h>
```

But, when trying to finally build entire the app with `make` get an error like:
```
undefined reference to `SQLite::OPEN_READWRITE`
...
```

Seems following configuration not enough in `Makefile`?
```
pkg-config --libs --cflags sqlite3
```

**Comment by UnixY2K** [comment]
I think the package no longer has a maintainer in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051207
you can check if it works using the latest version here (3.3.2), both cmake or meson can create the required pkgconf so you can test it
