### ISSUE TITLE
Bug when compile with sqlite 3.34.0

### ISSUE THREAD

**Issue by paulocoutinhox** [SRombauts/SQLiteCpp#315]
Hi,

Im getting the following error:

```
[ 85%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
/Users/paulo/.conan/data/sqlitecpp/3.1.1/_/_/build/518d5483cdb53cc130fd28cdad883cd2b4d0a54f/source_subfolder/src/Database.cpp:213:11: error: use of undeclared identifier
      'sqlite3_load_extension'
    ret = sqlite3_load_extension(getHandle(), apExtensionName, apEntryPointName, 0);
          ^
1 error generated.
```

Can you help me?

**Comment by SRombauts** [comment]
Hi! 
Thanks for reporting, though I don't see how that would be possible.
Nothing is ever removed in SQLite https://sqlite.org/changes.html

I suspect that you might be trying to link against à pre-built SQLite version were the extension mechanism is disabled. 

Let me know

**Comment by paulo-coutinho** [comment]
I revert it and i'm using version 2.5.0 and this problem don't happen.

**Comment by paulo-coutinho** [comment]
It only happen for iOS, because on other platform it don't happen.

If i change from:
```
self.requires("sqlitecpp/2.5.0")
```

to:
```
self.requires("sqlitecpp/3.1.1")
```

The error happen.

**Comment by paulo-coutinho** [comment]
I checked now that it happen with sqlitecpp/2.5.0 too:

```
[ 14%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
[ 57%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
[ 57%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o
[ 57%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Exception.cpp.o
[ 71%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.o
[ 85%] Building CXX object source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
[ 85%] Built target SQLiteCpp_cppcheck
/Users/paulo/.conan/data/sqlitecpp/2.5.0/_/_/build/6c6976ef6d6fe782762f8ccbdac6a87e4a73c0f2/source_subfolder/src/Database.cpp:233:11: error: use of undeclared identifier 'sqlite3_load_extension'
    ret = sqlite3_load_extension(mpSQLite, apExtensionName, apEntryPointName, 0);
          ^
/Users/paulo/.conan/data/sqlitecpp/2.5.0/_/_/build/6c6976ef6d6fe782762f8ccbdac6a87e4a73c0f2/source_subfolder/src/Database.cpp:330:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
    if (!strncmp(pHeaderStr, "SQLite format 3", 15) == 0)
        ^                                           ~~
/Users/paulo/.conan/data/sqlitecpp/2.5.0/_/_/build/6c6976ef6d6fe782762f8ccbdac6a87e4a73c0f2/source_subfolder/src/Database.cpp:330:9: note: add parentheses after the '!' to evaluate the comparison first
    if (!strncmp(pHeaderStr, "SQLite format 3", 15) == 0)
        ^
         (                                              )
/Users/paulo/.conan/data/sqlitecpp/2.5.0/_/_/build/6c6976ef6d6fe782762f8ccbdac6a87e4a73c0f2/source_subfolder/src/Database.cpp:330:9: note: add parentheses around left hand side expression to silence this warning
    if (!strncmp(pHeaderStr, "SQLite format 3", 15) == 0)
        ^
        (                                          )
1 warning and 1 error generated.
make[2]: *** [source_subfolder/CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [source_subfolder/CMakeFiles/SQLiteCpp.dir/all] Error 2
make: *** [all] Error 2
```

What i can do to solve it?

**Comment by paulo-coutinho** [comment]
This is very very crazy...i have execute the build process again and it compile without problems o.o
